apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # labels:
  #   kubernetes.io/bootstrapping: rbac-defaults
  name: istio-networking-controller
rules:
- apiGroups:
  - "networking.istio.io"
  resources:
  - virtualservices
  - destinationrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: system:serviceaccount:default:istio-networking-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:default:default
