apiVersion: v1
kind: Service
metadata:
  name: k8s-api-test
  # namespace: bmi
  labels:
    app: k8s-api-test
spec:
  ports:
  - port: 8080
    targetPort: 8882
    name: http-k8s-api-test
  # externalIPs: [192.168.43.70]
  selector:
    app: k8s-api-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-api-test
  # namespace: bmi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-api-test
        version: v1
    spec:
      containers:
      - name: k8s-api-test
        image: juzhen/k8s-api-test:v1
        imagePullPolicy: IfNotPresent
        # ports:
        # - containerPort: 8882
---

